[2024-04-29T12:51:32.715+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T12:51:32.811+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: immo_eliza.cleaning manual__2024-04-29T12:51:24.990949+00:00 [queued]>
[2024-04-29T12:51:32.831+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: immo_eliza.cleaning manual__2024-04-29T12:51:24.990949+00:00 [queued]>
[2024-04-29T12:51:32.832+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-29T12:51:32.870+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): cleaning> on 2024-04-29 12:51:24.990949+00:00
[2024-04-29T12:51:32.890+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1288) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T12:51:32.894+0000] {standard_task_runner.py:63} INFO - Started process 1321 to run task
[2024-04-29T12:51:32.891+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'immo_eliza', 'cleaning', 'manual__2024-04-29T12:51:24.990949+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/eliza.py', '--cfg-path', '/tmp/tmpe09m2a9r']
[2024-04-29T12:51:32.900+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask cleaning
[2024-04-29T12:51:33.062+0000] {task_command.py:426} INFO - Running <TaskInstance: immo_eliza.cleaning manual__2024-04-29T12:51:24.990949+00:00 [running]> on host 2f572e0ad8bc
[2024-04-29T12:51:33.383+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='immo_eliza' AIRFLOW_CTX_TASK_ID='cleaning' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T12:51:24.990949+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T12:51:24.990949+00:00'
[2024-04-29T12:51:33.387+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T12:51:35.149+0000] {warnings.py:110} WARNING - /opt/***/dags/eliza/machinelearning/preprocess.py:16: DtypeWarning: Columns (0,2,3,4,5,6,9,11,12,13,14,15,16,18,19,20,21,22,24,25,29,31,38,39,40,42,43,44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(newpath)

[2024-04-29T12:58:29.814+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T12:58:29.815+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/eliza/machinelearning/preprocess.py", line 457, in cleaning
    filled_data = fill_empty_data(converted_data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/eliza/machinelearning/preprocess.py", line 27, in fill_empty_data
    df["Fireplace Count"].abs().fillna(1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 1652, in abs
    res_mgr = self._mgr.apply(np.abs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = b.apply(f, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/blocks.py", line 366, in apply
    result = func(self.values, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bad operand type for abs(): 'str'
[2024-04-29T12:58:29.833+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=immo_eliza, task_id=cleaning, execution_date=20240429T125124, start_date=20240429T125132, end_date=20240429T125829
[2024-04-29T12:58:29.849+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task cleaning (bad operand type for abs(): 'str'; 1321)
[2024-04-29T12:58:29.876+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-29T12:58:29.899+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T12:58:29.903+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
