[2024-05-02T11:08:16.925+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-02T11:08:16.958+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: immo_eliza.cleaning scheduled__2024-05-01T00:00:00+00:00 [queued]>
[2024-05-02T11:08:16.969+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: immo_eliza.cleaning scheduled__2024-05-01T00:00:00+00:00 [queued]>
[2024-05-02T11:08:16.970+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-02T11:08:16.992+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): cleaning> on 2024-05-01 00:00:00+00:00
[2024-05-02T11:08:17.005+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2273) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-02T11:08:17.008+0000] {standard_task_runner.py:63} INFO - Started process 2293 to run task
[2024-05-02T11:08:17.006+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'immo_eliza', 'cleaning', 'scheduled__2024-05-01T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/eliza.py', '--cfg-path', '/tmp/tmp6png0o6u']
[2024-05-02T11:08:17.009+0000] {standard_task_runner.py:91} INFO - Job 39: Subtask cleaning
[2024-05-02T11:08:17.078+0000] {task_command.py:426} INFO - Running <TaskInstance: immo_eliza.cleaning scheduled__2024-05-01T00:00:00+00:00 [running]> on host 2f572e0ad8bc
[2024-05-02T11:08:17.258+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='immo_eliza' AIRFLOW_CTX_TASK_ID='cleaning' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-01T00:00:00+00:00'
[2024-05-02T11:08:17.261+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-02T11:08:20.098+0000] {warnings.py:110} WARNING - /opt/***/dags/eliza/machinelearning/preprocess.py:16: DtypeWarning: Columns (0,2,3,4,5,6,9,11,12,13,14,15,16,18,19,20,21,22,24,25,29,31,38,39,40,42,43,44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(newpath)

[2024-05-02T11:34:11.674+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-02T11:34:11.676+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/eliza/machinelearning/preprocess.py", line 457, in cleaning
    filled_data = fill_empty_data(converted_data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/eliza/machinelearning/preprocess.py", line 27, in fill_empty_data
    df["Fireplace Count"].abs().fillna(1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 1652, in abs
    res_mgr = self._mgr.apply(np.abs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = b.apply(f, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/blocks.py", line 366, in apply
    result = func(self.values, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bad operand type for abs(): 'str'
[2024-05-02T11:34:11.706+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=immo_eliza, task_id=cleaning, execution_date=20240501T000000, start_date=20240502T110816, end_date=20240502T113411
[2024-05-02T11:34:11.730+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 39 for task cleaning (bad operand type for abs(): 'str'; 2293)
[2024-05-02T11:34:11.769+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-02T11:34:11.797+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-02T11:34:11.802+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
